spring.application.name=invenario_web
spring.thymeleaf.cache=false
storage.location=C:/temp/inventario/planos

# =========================================================
# BASE DE DATOS 1: INVENTARIO (Principal)
# =========================================================
app.datasource.inventario.url=jdbc:mysql://localhost:3306/inventario_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app.datasource.inventario.username=root
app.datasource.inventario.password=
app.datasource.inventario.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# BASE DE DATOS 2: LISTIN
# =========================================================
app.datasource.listin.url=jdbc:mysql://localhost:3306/listin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
app.datasource.listin.username=root
app.datasource.listin.password=
app.datasource.listin.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true